# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://hitpeterfeng.github.io
date_format: "ordinal"
title: Fighting for a better life!
subtitle: "Fighting!"
description: "hitpeterfeng的个人博客"
keywords: HIT, FENG
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: FENG Yang
organization: undecided
organization_url: www.google.com
github_username: hitpeterfeng
location: Beijing, China
email: hit.yang.feng@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: hitpeterfeng/hitpeterfeng.github.io

# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: gitalk
gitalk:
    owner: hitpeterfeng
    enable: true    #是否开启Gitalk评论
    clientID: 240624039eb6f2b079ec
    clientSecret: b255b099d214454020bd8944020b936103cc00e5
    repo: blog-comments.github.io
    admin: hitpeterfeng
    distractionFreeMode: true
    labels: ['Gitalk']

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
