# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://hitpeterfeng.github.io
date_format: "ordinal"
title: Fighting for a better life!
subtitle: "Fighting!"
description: "hitpeterfeng的个人博客"
keywords: HIT, FENG
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: FENG Yang
organization: undecided
organization_url: www.google.com
github_username: hitpeterfeng
location: Beijing, China
email: hit.yang.feng@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: hitpeterfeng/hitpeterfeng.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# https://disqus.com
disqus:
   username: disqus_hitpeterfeng
# # https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: hitpeterfeng
#     repo: blog-comments
#     oauth:
#         client_id: feb39c1d04715b966dc4
#         client_secret: 52d70c3786f17bda45f9bef78e1d5ed9d98d23c1
# # https://github.com/gitalk/gitalk#install
gitalk:
    owner: hitpeterfeng
    repo: blog-comment
    clientID: b910303d85f6cb1ace68
    clientSecret: af8a428a4161c23baf6d38147772d2f7a3536be7
    distractionFreeMode: true
# # 在使用其它评论组件时可点击显示 Disqus
# lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
